var self = this,
    body = $(document.body),
    doc = $(document),
    docWindow = $(window),
    bodyPosition = {
        top: false,
        left: false
    },
    token360 = $("#gt-is-360"),
    token480 = $("#gt-is-480"),
    token667 = $("#gt-is-667"),
    token768 = $("#gt-is-768"),
    token1024 = $("#gt-is-1024"),
    token1231 = $("#gt-is-1231"),
    gtHeader = $("header"),
    gtFooter = $("footer"),
    gtWrapper = $("#gt-wrapper"),
    upButton = $("#gt-up"),
    mobileMenuSwitch = $("#gt-mobile-menu-switch"),
    enterButton = $('.gt-enter'),
    enterWrapper = $('#gt-header-enter-wrapper'),
    enterForm = $('#gt-header-enter'),
    enterChose = $('#gt-header-enter-chose'),
    enterClose = $('#gt-header-enter-close');