var self = this,
    body = $(document.body),
    doc = $(document),
    docWindow = $(window),
    bodyPosition = {
        top: false,
        left: false
    },
    gtHeader = $("#header"),
    gtFooter = $("footer"),
    gtWrapper = $("#gt-wrapper"),
    upButton = $("#gt-up"),
    openSearchBtn = $('#gt-open-search'),
    mobileMenuSwitch = $("#gt-mobile-menu-switch"),
    enterButton = $('#gt-enter'),
    headerUser = $('#gt-header-user'),
    enterWrapper = $('#gt-header-enter-wrapper'),
    enterForm = $('#gt-header-enter'),
    userMenuOpen = false,
    enterChose = $('#gt-header-enter-chose'),
    enterClose = $('#gt-header-enter-close');